spring.application.name=PruebaTecnica-MVC
server.port= 9000
spring.jpa.hibernate.ddl-auto = create
spring.datasource.url = jdbc:postgresql://localhost:5432/PruebaTecnica
spring.datasource.username = postgres
spring.datasource.password = 1907
